### ISSUE TITLE
Contribution Request : OSCAL example that points to MITRE and describes tests using Gherkin

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#11]
## Description
During #5 the following requests were raised by the CCC MITRE working group.

- [ ] Can Citi contribute an existing OSCAL example that can be used as a reference by the MITRE working group?
  - This example could be used to inform further MITRE contributions through OSCAL.
  - Can this contribution be raised as a PR into the CCC repo?

- [ ] The work related to `Storage ( object storage ) [AWS S3, gcp storage, azure object storage]` is complete and ready to be contributed into the FINOS CCC repo 
  - https://github.com/finos/common-cloud-controls/issues/11#issuecomment-1729746032

--- Update ---

The following item has been moved into its own separate issue as it creates a larger scope.
- Gherkin should be used as a `Behaviour Test` rather than a `Configuration Test`. 
  - Can an example of this type of test be expanded upon during a relevant future call?

**Comment by AdrianHammond** [comment]
@eddie-knight  - this look good. 

@mark-rushing @moematar @simonzhangbmo @vicenteherrera  - what do you think? Are you okay with this and should we #72 ?

**Comment by mark-rushing** [comment]
It looks great! Think it would be good to run services/database/relational/rdms-taxonomy.feature past the other two working groups <- @jonmuk @git-hub-forwork1


From: "[github.com] Adrian Hammond" ***@***.***>
Reply-To: finos/common-cloud-controls ***@***.***>
Date: Tuesday, October 24, 2023 at 2:23 AM
To: finos/common-cloud-controls ***@***.***>
Cc: "Rushing, Mark [CCC-OT]" ***@***.***>, Mention ***@***.***>
Subject: Re: [finos/common-cloud-controls] Contribution Request : OSCAL example that points to MITRE and describes tests using Gherkin (Issue #11)

@eddie-knight - this look good. @mark-rushing @moematar @simonzhangbmo @vicenteherrera - what do you think? Are you okay with this and should we #72 ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving


@eddie-knight<https://urldefense.com/v3/__https:/github.com/eddie-knight__;!!Jkho33Y!iLEEHhLyqR_NxpRdRQZqG4PfuW2yDBRQfQpuJor3uCsotc-6jktUzgJQnpZH5t5M6qBG-IXZDkRnY1GvZccRQgZG$> - this look good.

@mark-rushing<https://urldefense.com/v3/__https:/github.com/mark-rushing__;!!Jkho33Y!iLEEHhLyqR_NxpRdRQZqG4PfuW2yDBRQfQpuJor3uCsotc-6jktUzgJQnpZH5t5M6qBG-IXZDkRnY1GvZXFOrtJF$> @moematar<https://urldefense.com/v3/__https:/github.com/moematar__;!!Jkho33Y!iLEEHhLyqR_NxpRdRQZqG4PfuW2yDBRQfQpuJor3uCsotc-6jktUzgJQnpZH5t5M6qBG-IXZDkRnY1GvZYdYCDX2$> @simonzhangbmo<https://urldefense.com/v3/__https:/github.com/simonzhangbmo__;!!Jkho33Y!iLEEHhLyqR_NxpRdRQZqG4PfuW2yDBRQfQpuJor3uCsotc-6jktUzgJQnpZH5t5M6qBG-IXZDkRnY1GvZdsIDmP4$> @vicenteherrera<https://urldefense.com/v3/__https:/github.com/vicenteherrera__;!!Jkho33Y!iLEEHhLyqR_NxpRdRQZqG4PfuW2yDBRQfQpuJor3uCsotc-6jktUzgJQnpZH5t5M6qBG-IXZDkRnY1GvZSFYerJw$> - what do you think? Are you okay with this and should we #72<https://urldefense.com/v3/__https:/github.com/finos/common-cloud-controls/pull/72__;!!Jkho33Y!iLEEHhLyqR_NxpRdRQZqG4PfuW2yDBRQfQpuJor3uCsotc-6jktUzgJQnpZH5t5M6qBG-IXZDkRnY1GvZdTrpSjf$> ?

**Comment by AdrianHammond** [comment]
@mark-rushing @jonmuk @git-hub-forwork1  - @eddie-knight has resubmitted new PR #82 as original PR closed and could not be reopened. Are you okay if I merge this PR and then we iterate on it? Eddie is presenting in [NYC](https://sched.co/1PzGv) next week and it would be useful to have the initial view of the taxonomy in the repo.  Thanks

**Comment by rgriffiths-scottlogic** [comment]
Is Gherkin the only contender here? Or are there other options?
