### ISSUE TITLE
January 4th 2024 - Common Cloud Controls Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/common-cloud-controls#110]
## Date
January 4th 2024 - 12pm EST / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes

**Comment by maoo** [comment]
@maoo / FINOS

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by robmoffat** [comment]
Rob Moffat - FINOS

**Comment by vicenteherrera** [comment]
Vicente Herrera / Control Plane

**Comment by rgriffiths-scottlogic** [comment]
Robert Griffiths - Scott Logic

**Comment by AdrianHammond** [comment]
Hi 😄  Adrian Hammond / Red Hat

**Comment by njwilliams** [comment]
Nick Williams / Morgan Stanley

**Comment by aric-rosenbaum** [comment]
Aric Rosenbaum / Red Hat (Happy New Year to all)

**Comment by leefaus** [comment]
Lee Faus / GitLab

**Comment by simonzhangbmo** [comment]
simon zhang/BMO

**Comment by rachkim00** [comment]
Rachel Kim/Google

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by iMichaela** [comment]
Michaela Iorga/NIST

**Comment by nas-hub** [comment]
Naseer Mohammad / Google

**Comment by robmoffat** [comment]
## Minutes

- #101 Discussed whether to create distribution lists.  Some discussion about Matrix as a discussion tool.
- #75 Discussed progress on OSCAL representation 
- #108 Discussed Mao's change to the template - @robmoffat approved
- #107 Discussed ControlPlane PR - EasyCLA blocking at the moment
