### ISSUE TITLE
Do we want to create a document to contain Architectural Design Records (ADR)s?

### ISSUE THREAD

**Issue by robmoffat** [finos/common-cloud-controls#113]
## Feature Request

@iMichaela suggested as we make decisions we store these somewhere. Two suggestions:

 - Use the GitHub Wiki features
 - Create a document to store all these decisions

This came up as a result of discussing #43

**Comment by robmoffat** [comment]
@eddie-knight suggested this could be added to the CONTRIBUTING.md file.

**Comment by robmoffat** [comment]
@crawfordchanel - assigned to decide which working group is best to decide this.  e.g. Steering Committee, All Hands, etc.

**Comment by iMichaela** [comment]
> @crawfordchanel - assigned to decide which working group is best to decide this. e.g. Steering Committee, All Hands, etc.

In my mind, each WG can generate their ADRs. Alternatively, Wiki can  be used to document the decisions.
