### ISSUE TITLE
Invite MITRE to join the next working group call on September 21st at 12pm EST / 5pm BST

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#12]
## Description

- [ ] Invite MITRE to join the next working group call on September 21st at 12pm EST / 5pm BST 

## Purpose
To understand how the group can contribute back to the MITRE framework.

**Comment by mcleo-d** [comment]
Hi @crawfordchanel - Can you work with @git-hub-forwork1 to move this forward as it would be awesome to invite MITRE to the next working group call - #91

**Comment by crawfordchanel** [comment]
Yes. I will reach out to Jason for an update.

Thank you!

Chanel

**Comment by selgags** [comment]
@mcleo-d, do we need to prepare any material go over on the call with MITRE team?

**Comment by crawfordchanel** [comment]
MITRE has been engaged as per issue #103 This issue is eligible for closure.

**Comment by crawfordchanel** [comment]
MITRE active in project
