### ISSUE TITLE
Add Compute (VM) to Services

### ISSUE THREAD

**Issue by AdrianHammond** [finos/common-cloud-controls#132]
## Feature Request

Add Cloud Compute (VM) to CCC services. 

### Description of Problem:

The CFI project is working with FSISAC on creating referencing architectures, the first architecture is a three tier app e.g. this is an example from [Google](https://cloud.google.com/architecture/single-zone-deployment-compute-engine). 

The architecture contains four services, load balancer, compute (VM), database and storage bucket. 

The purpose of this issue to to create a service taxonomy for compute. 

### Potential Solutions:

The high level description of [compute](https://github.com/finos/common-cloud-controls/blob/main/services/compute-services.md) already exists, what is required is the common compute capabilities in same details as we created for [relational database](https://github.com/finos/common-cloud-controls/tree/main/services/database/relational)

**Comment by jisted-scottlogic** [comment]
Taking on this work.
Joshua Isted, Scott Logic

**Comment by AdrianHammond** [comment]
PR #147 for this issue is ready for review.
