### ISSUE TITLE
Add Cloud Load Balancer to CCC service taxonomy

### ISSUE THREAD

**Issue by AdrianHammond** [finos/common-cloud-controls#133]
## Feature Request

Add Cloud Load Balancer to CCC service taxonomy

### Description of Problem:

The CFI project is working with FSISAC on creating referencing architectures, the first architecture is a three tier app e.g. this is an example from [Google](https://cloud.google.com/architecture/single-zone-deployment-compute-engine). 

The architecture contains four services, load balancer, compute (VM), database and storage bucket. 

The purpose of this issue to to create a service taxonomy for cloud load balancer. 

### Potential Solutions:

The high level description of [load balancer](https://github.com/finos/common-cloud-controls/blob/main/services/networking-services.md#load-balancing) already exists, what is required is the common *load balancer* capabilities in same details as we created for [relational database](https://github.com/finos/common-cloud-controls/tree/main/services/database/relational)

**Comment by smendis-scottlogic** [comment]
We from Scott Logic would like to work on this issue.

**Comment by rgriffiths-scottlogic** [comment]
Hi Chanel,

Could you please add Cara Fisher as an assignee?

Thanks,

Rob
________________________________

**Comment by AdrianHammond** [comment]
PR #149 has been opened for this issue and is ready for review.

**Comment by AdrianHammond** [comment]
Closing after merge of #149  - thanks to everyone who contributed / commented on this issue.
