### ISSUE TITLE
Add Cloud Storage to CCC service taxonomy

### ISSUE THREAD

**Issue by AdrianHammond** [finos/common-cloud-controls#134]
## Feature Request

Add Cloud Storage (Block) to CCC service taxonomy

### Description of Problem:

The CFI project is working with FSISAC on creating referencing architectures, the first architecture is a three tier app e.g. this is an example from [Google](https://cloud.google.com/architecture/single-zone-deployment-compute-engine). 

The architecture contains four services, load balancer, compute (VM), database and storage bucket. 

The purpose of this issue to to create a service taxonomy for cloud load balancer. 

### Potential Solutions:

The high level description of [storage](https://github.com/finos/common-cloud-controls/blob/main/services/storage-services.md) already exists, what is required is the common *storage* capabilities in same details as we created for [relational database](https://github.com/finos/common-cloud-controls/tree/main/services/database/relational)

**Comment by robmoffat** [comment]
Discussed with @smendis-scottlogic @rgriffiths-scottlogic and @eddie-knight - starting here, will attempt to have something ready for show-and-tell in the CCC All-Hands meeting on 7th March.

**Comment by smendis-scottlogic** [comment]
I can do the Object Storage Taxonomy

**Comment by robmoffat** [comment]
@eddie-knight will contribute a .feature file for this

**Comment by smendis-scottlogic** [comment]
Created a PR for this work. Please review @eddie-knight
