### ISSUE TITLE
Inaugural SteerCo Self-Nomination

### ISSUE THREAD

**Issue by eddie-knight** [finos/common-cloud-controls#150]
Howdy folks— we're going through a bit of a restart with the CCC community governance, starting with the changes implemented in PR #144.

**Please do not comment on this issue without reading the context below in full.**

As part of the new SteerCo charter, we will have 7 folks who are responsible to delegate and empower the rest of the community according to the mission and vision of Common Cloud Controls.

Future appointments to the steering committee will involve annual elections, but **the first SteerCo appointments will be made by the FINOS Board of Directors, based on self-nominations and community feedback on this issue.**

There are 4 reserved seats and 3 community seats, which I will share more about below.

## Role of a Steering Committee Member

You can read more about the responsibilities of the steering committee in the group charter and bootstrap notes, but I'll highlight the salient points here.

**You are:**

- A structurally minded person with interests in the financial services space
- A reputable cybersecurity generalist, or expert in a specific subfield of cybersecurity
- Available for at least 8 weekly recurring meetings to kickstart the community
- Available to give ad hoc responses to non-technical issues throughout your term
- Available for mandatory quarterly meetings to review the progress being made by the community

**You will:**

- Identify the high-level needs of the community
- Charter community groups to tackle specific topics
- Appoint leads for each chartered community group, in adherence with the respective charter
- Revoke the charter of groups who have completed their charter or proven ineffectual
- Be listed by name on the project's top README.md

**In order to be eligible for voting, an individual must:**

- Be an FINOS Member who had a substantial contribution to the CCC project within 12 months prior to their nomination. Contributions include GitHub events like creating issues, creating PRs, reviewing PRs, commenting on issues, etc.
- Demonstrate expertise in any subfield of cybersecurity, or general working experience in cybersecurity for financial services, within 2 years prior to their nomination.

## Reserved and Community Seats

In order to ensure that CCC is known as a standard created by and for financial services institutions, it is essential that no fewer than 4 of the 7 members represent different FSIs. No two organizations may be represented in these seats, and all four must be filled by folks who are currently employed directly by FSIs. 

(A 30-day grace period exists for anyone changing roles while holding a Steering Committee seat.)

The remaining 3 seats may be filled by anyone in the community, including duplicates organizations or non-FSI roles... but for the sake of the steerco bootstrapping process, **the community has requested that only one member from each organization be represented in the inaugural 7 members.**

## How to self-nominate

Please comment on this issue in the following structure:

```
**Name:** <your name>
**Company:** <your direct employer>
**Experience:** <one sentence summarizing your cybersecurity experience> 
**Seat:** <"Reserved" or "Community">
```

If you are submitting for a Reserved seat, please check with your organization to ensure that you have only one nomination per company this time. This will help streamline the bootstrapping process significantly.

For the sake of clarity, I'll go ahead and nominate myself using the first comment to kick things off.

## How to Show Support

With guidance from the FINOS Technical Oversight Committee, the FINOS Board of Directors will be asked to consider nominations that best fit the eligibility criteria and carry the most support from the community. You may show your support for any number of nominations by using a thumbs up emoji (👍) on the self-nomination comment.

Yes, you may use multiple different reactions to show overwhelming support if you feel particularly inclined.

**Please do not comment on the issue with anything aside from self-nominations.** If you want, you can always use the community mailing list for discussion (ccc-participants@lists.finos.org).

## Deadline and Next Steps

Nominations will be presented to the board for consideration on April 8th. Submissions will be compiled on April 7th in preparation for the Board presentation. Earlier submissions are recommended, as this will allow you to receive more community support.

The Board's final decision will be communicated via the community mailing list (ccc-participants@lists.finos.org) no later than April 12th.

**Comment by eddie-knight** [comment]
**Name:** Eddie Knight
**Company:** Sonatype
**Experience:** I specialize in open source project security and compliance, including leadership and technical contributions on the _FINOS CFI_ project and the _CNCF Security Technical Advisory Group_.
**Seat:** Community

**Comment by AdrianHammond** [comment]
Name: Adrian Hammond
Company: Red Hat
Experience: Chief Architect supporting FSI clients in hybrid cloud architectures. Contributor to FINOS CFI and have been a maintainer for two years, also maintainer for CCC and contributing to Taxonomy working group. 
Seat: Community

**Comment by simonzhangbmo** [comment]
Name: Simon Zhang
Company: BMO
Experience: Led Cloud Architecture development and implementation for 7 years. Familiar with AWS and Azure. AWS Certified Solution Architect - Professional

**Comment by rgriffiths-scottlogic** [comment]
Name: Robert Griffiths
Company: Scott Logic
Experience: Principal Consultant supporting FSI clients (mainly) with their cloud transformation journeys. Prior experience includes running Cloud & High Performance Computing for a G-SIFI (MUFG) where I also worked closely with Microsoft to develop and refine its Azure offering for HPC in FSI. Currently leading the team at Scott Logic that's contributing to the Taxonomy Working Group.
Seat: Community

**Comment by crawfordchanel** [comment]
On behalf of Jonathan Meadows: 

Name: Jonathan Meadows
Company: Citi Bank
Experience: Managing Director and Open Source expert with 30 years experience in Cybersecurity for the Financial Services Industry
Seat: Financial Services

**Comment by ojeb2** [comment]
**Name:** Oli Bage
**Company:** LSEG
**Experience:** Head of Architecture, Data & Analytics at LSEG working with Azure, AWS and GCP day to day to deliver LSEG's current data, analytics and software to FS clients and build our next generation of services on cloud.  Founder Cloud Data Management Capabilities (CDMC) automated control frame work, co-delivered with 17 systemically important banks with AWS, Azure, GCP & IBM Cloud.  FinOS exec sponsor for LSEG.  Lead or contribute to multiple EDMCouncil Data & AI working groups, the OMG/EKGF Data Product standard, FinOS CCC & Architecture as Code projects and Open Data Institute industry group.  
**Seat:** Financial Services (although LSEG is both a regulated FS firm and an FS Community partner)

**Comment by eddie-knight** [comment]
This has been presented to the board and next steps will be presented to the community on the next scheduled call (April 18 2024), along with an update to this repo. Thanks everyone for your participation!
