### ISSUE TITLE
Further Research of VM Taxonomy

### ISSUE THREAD

**Issue by AdrianHammond** [finos/common-cloud-controls#154]
### Description of Problem:
During the review of #147 a suggestion was made that further research/enhancement was needed.

_Should we create a subset of the most used taxonomy features?
If so, how do we identify which taxonomy features will be included in that subset? We may need to do additional research on this.
e.g Users in AWS may not prefer to use General/Storage optimized EC2 instances, whereas GCP users may prefer to use GPU/AI-focused instances or compute engines._

**Comment by markrushing** [comment]
I am not sure I understand the value of the subset of commonly used features. One of the key issues with a CSP service is that even if you don’t intend to use a feature you need to have controls for it to assure it is not used.
