### ISSUE TITLE
Evaluate alignment with CNCF Compliance efforts

### ISSUE THREAD

**Issue by eddie-knight** [finos/common-cloud-controls#199]
Within the CNCF Security Technical Advisory Group, there have been efforts in the past to [map](https://docs.google.com/spreadsheets/d/1GUohOTlLw9FKUQ3O23X7ypvJLXN-B3veJGe6YE6JYfU/edit#gid=1938257679) NIST 800-53r5 controls to the recommendations in their [publications](https://github.com/cncf/tag-security/tree/main/publications).

Will these mappings help accelerate any of the work we're doing?

Separately... Considering our efforts to define regulatory compliance for cloud services, is there any opportunity for overlap with the CNCF STAG [Compliance Working Group](https://github.com/cncf/tag-security/tree/main/compliance)?

**Comment by mlysaght2017** [comment]
@eddie-knight @jared-lambert  - I spoke to Jon Zeolla about the CNCF cloud native control catalog and also looked at some of their best practices you've pointed to here. The CNCF catalog is K8s focused, and from I can see, does not have a focus on CSP cloud services. I believe the codified templates being proposed for the CCC control go beyond what's detailed in the CNCF catalog so far and I'm happy with the progress we're making on that front.

**Comment by jared-lambert** [comment]
Michael to write a considerations article / para that outlines this call, and put it in the resources folder for later discovery if needed.

**Comment by jared-lambert** [comment]
For the STAG area, we created a new item here:
https://github.com/finos/common-cloud-controls/issues/278
