### ISSUE TITLE
06/13/2024 Common Cloud Controls Meeting- Taxonomy Working Group

### ISSUE THREAD

**Issue by smendis-scottlogic** [finos/common-cloud-controls#201]
## Date
06/13/2024 - 11:30am ET / 4:30pm UK

## Untracked attendees
- Fullname, Affiliation, Capacity (Contributor/Advisor/Observer)

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Log attendance via comments
- [x] Appoint minute taker
- [x] Approve past meeting minutes
- [x] [Project board](https://github.com/orgs/finos/projects/78/views/2) walkthrough (filter by WG label, start right to left)
- [x] Align requirements of Security WG to Taxonomy WG
- [x] Understand how to create feature sets for defined Taxonomies
- [x] Call for volunteers to join the WG
- [ ] AOB, Q&A & Adjourn (5mins)

### Zoom info
[https://zoom.us/j/94109603410](https://www.google.com/url?q=https://zoom.us/j/94109603410&sa=D&source=calendar&ust=1718716004204488&usg=AOvVaw0YJC0LUhaFsGKQMnG5jcN4)
Meeting ID: 941 0960 3410
Passcode: 353234

**Comment by eddie-knight** [comment]
:wave: :shipit: Eddie Knight / Sonatype

**Comment by nas-hub** [comment]
Naseer Mohammad / Google

**Comment by TheJuanAndOnly99** [comment]
Juan Estrella / FINOS 
FINOS support for any questions please reach out to help@finos.org! :)

**Comment by mlysaght2017** [comment]
Michael Lysaght/Citi/Advisor

**Comment by eziogas-scottlogic** [comment]
Euthyme Ziogas / Scott Logic / Observer

**Comment by eddie-knight** [comment]
**Meeting Notes (In Progress):**

Today's goal is to solicit feedback from the Security WG (Michael is present)

**Comment by fossil-creek** [comment]
Eric Peeters / Weaver

**Comment by smendis-scottlogic** [comment]
Sonali Mendis / Scott Logic / Contributor
