### ISSUE TITLE
06/20/2024 - Common Cloud Controls Meeting Minutes - Delivery Working Group

### ISSUE THREAD

**Issue by damienjburks** [finos/common-cloud-controls#219]
## Date
06/20/2024 - 11:30am ET / 4:30pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal, or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] [Delivery Kanban](https://github.com/orgs/finos/projects/78/views/8) walkthrough
- [x] Discuss Epic Level Issues
   - [x] https://github.com/finos/common-cloud-controls/issues/183
   - [x] https://github.com/finos/common-cloud-controls/issues/184
- [x] AOB, Q&A & Adjourn (5mins)

### Zoom info

FINOS CCC - 2 is inviting you to a scheduled Zoom meeting.

Topic: FINOS CCC - 2's Personal Meeting Room

Join Zoom Meeting
https://zoom.us/j/9274196808

Meeting ID: 927 419 6808

---

One tap mobile
+13462487799,,9274196808# US (Houston)
+16694449171,,9274196808# US

---

Dial by your location
• +1 346 248 7799 US (Houston)
• +1 669 444 9171 US
• +1 669 900 6833 US (San Jose)
• +1 719 359 4580 US
• +1 253 205 0468 US
• +1 253 215 8782 US (Tacoma)
• +1 312 626 6799 US (Chicago)
• +1 360 209 5623 US
• +1 386 347 5053 US
• +1 507 473 4847 US
• +1 564 217 2000 US
• +1 646 931 3860 US
• +1 689 278 1000 US
• +1 929 205 6099 US (New York)
• +1 301 715 8592 US (Washington DC)
• +1 305 224 1968 US
• +1 309 205 3325 US
• 877 853 5247 US Toll-free
• 888 788 0099 US Toll-free

Meeting ID: 927 419 6808

Find your local number: https://zoom.us/u/abrCfygln

**Comment by eddie-knight** [comment]
:wave: :shipit: Eddie Knight / Sonatype

**Comment by mlysaght2017** [comment]
Michael L/Citi
