### ISSUE TITLE
06/20/2024 All Hands Meeting Minutes

### ISSUE THREAD

**Issue by eddie-knight** [finos/common-cloud-controls#221]
## Date

06/20/2024 - 1200 ET / 1700 UK

- [Join Zoom Meeting](https://zoom.us/j/94416168360)
- Meeting ID: 944 1616 8360
- Passcode: 042805
- [Find your local number](https://zoom.us/u/apjhwwA3K)
- [Copy this meeting to your calendar](calendar.finos.org)

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).
- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).
- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.
- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] [Project board](https://github.com/orgs/finos/projects/78/views/11) walkthrough
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

**Comment by eddie-knight** [comment]
:wave: :shipit: Eddie Knight / Sonatype

**Comment by eziogas-scottlogic** [comment]
Euthyme Ziogas / Scott Logic / Observer

**Comment by Alexstpierrework** [comment]
Alex St. Pierre | METRO

**Comment by robmoffat** [comment]
Rob Moffat / FINOS 🍄

**Comment by abdullahsaf** [comment]
Abdullah Safdar / Citi

**Comment by mlysaght2017** [comment]
Michael L/Citi

**Comment by damienjburks** [comment]
Damien Burks / Citi 👋🏾
