### ISSUE TITLE
Add additional approvers to each WG

### ISSUE THREAD

**Issue by eddie-knight** [finos/common-cloud-controls#239]
### Description of Problem:

The current list of approvers for each WG includes only the leads of each working group. Because a contributor cannot approve their own pull request, a PR created by a WG Lead cannot be merged if it modifies a resource their WG owns.

### Potential Solutions:

In accordance with the [member roles guidelines](https://github.com/finos/common-cloud-controls/blob/main/docs/governance/community-guidelines/member-roles.md), add inaugural approvers to the [GitHub Team](https://github.com/orgs/finos/teams/common-cloud-controls/teams) corresponding to each working group.

Note that the guideline is not established as a firm policy, and WG leads can make personal judgment calls regarding the qualifications of their WG's approvers.

Also note that SteerCo members are not disqualified from being approvers, but we should try to minimize the number of WGs that any one person is an approver in.

```[tasklist]
### TODO
- [ ] Communications WG
- [x] Community Structure WG
- [ ] Duplication Reduction WG
- [ ] Taxonomy WG
- [ ] Security WG
- [ ] Delivery WG
```

**Comment by eddie-knight** [comment]
The requirement for another approver in @finos/ccc-wg-delivery is currently a blocker for #223.

It occurs to me that we may want to reach out to the SteerCo for support recruiting folks from underrepresented FSIs.

**Comment by eddie-knight** [comment]
The requirement for another approver in @finos/ccc-wg-security is also a blocker for https://github.com/finos/common-cloud-controls/pull/153.

**Comment by damienjburks** [comment]
@eddie-knight I'd like to be an approver for the @finos/ccc-wg-security. Is that allowed?

**Comment by eddie-knight** [comment]
I'm of the opinion that it's a stopgap, but it's up to Michael to determine how approvers are selected for his WG.

If we are having a hard time finding additional approvers, it might be good to discuss contributor recruitment with the Comms WG.

It may also be good to bring this up with the SteerCo via email or on our next call.
