### ISSUE TITLE
Evaluate taxonomy pre-existing options

### ISSUE THREAD

**Issue by jared-lambert** [finos/common-cloud-controls#247]

**Comment by jared-lambert** [comment]
Look into how groups like FOCUS, Terraform, and other cloud agnostic providers map and unify these concepts.

**Comment by robmoffat** [comment]
FOCUS: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/columns/servicecategory.md
