### ISSUE TITLE
Create Graph DB Taxonomy

### ISSUE THREAD

**Issue by smendis-scottlogic** [finos/common-cloud-controls#256]
Graph DB taxonomy should live under services>databases>graph-db
Taxonomy file need to be created
Correct numbering format needs to be followed (CCC.TX.DB.03.YYYY)
Feature file need to be created

**Comment by smendis-scottlogic** [comment]
@fossil-creek volunteered to do this

**Comment by fossil-creek** [comment]
@smendis-scottlogic Apologies for the lack of communication. I was out sick and am now back and catching up!

**Comment by robmoffat** [comment]
@fossil-creek any update on this?
