### ISSUE TITLE
07/18/2024 Security WG Meeting Minutes

### ISSUE THREAD

**Issue by mlysaght2017** [finos/common-cloud-controls#264]
## Date

07/18/2024 - 11 am ET / 4 pm UK

- [Join Zoom Meeting](https://zoom.us/j/99521272221)
- Meeting ID: 995 2127 2221
- Passcode: 128200
- [Copy this meeting to your calendar](calendar.finos.org)
- [Find your local number](https://zoom.us/u/aUVBvM9h)

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).
- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).
- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.
- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] [Project board](https://github.com/orgs/finos/projects/78/views/7) walkthrough
- [ ] Update on call with CSA team
- [ ] Update on working sessions since last WG call 
- [ ] Request for all to review new PR #188 
- [ ] Request for help on adding in new controls for object storage/other service
- [ ] How we'll tackle the Catalog Layer/Implementation Layer (Component Definition) balance via the PoCs
- [ ] AOB, Q&A & Adjourn (5mins)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

**Comment by damienjburks** [comment]
Damien Burks - Citi 👋

**Comment by eddie-knight** [comment]
:wave: :shipit: Eddie Knight / Sonatype

**Comment by vCTO** [comment]
Ted Newman / NatWest Group

**Comment by nas-hub** [comment]
Naseer Mohammad / Google

**Comment by iMichaela** [comment]
Michaela Iorga/NIST

**Comment by fossil-creek** [comment]
Eric Peeters / Weaver

**Comment by rowan-baker** [comment]
Rowan Baker / ControlPlane

**Comment by mlysaght2017** [comment]
ML: Convene and roll call
ML: Steps through usual Meeting Notices
ML: Opened Project Kanban
ML: Quick Intros from new joiners from NatWest
ML: Stepped group through PR #188 and requested reviews
Michaela: In context of #242 discussed work done by other projects that align with some of our challenges on control catalog representation in OSCAL, including https://www.emerald-he.eu/ 
ML: will schedule working sessions to move 242 forward next week.
