### ISSUE TITLE
Link Checking

### ISSUE THREAD

**Issue by robmoffat** [finos/common-cloud-controls#277]
## Feature Request

We are starting to look at controls / taxonomy items as markdown documents.  I have a feeling we are going to need some way of ensuring referential integrity.  Perhaps we could look at a GitHub action to do markdown link checking, e.g.  https://github.com/marketplace/actions/markdown-link-check
```[tasklist]
### Tasks
```

**Comment by iMichaela** [comment]
I use lychee for my websites generated from GH and the actions are scheduled every day.

**Comment by sshiells-scottlogic** [comment]
@dogle-scottlogic has made a PR for this.

There are currently 44 broken links. Shall we try to fix them as part of this PR or should those be handled separately (as likely in places owned by different codeowners).

**Comment by dogle-scottlogic** [comment]
> @dogle-scottlogic has made a PR for this.
> 
> There are currently 44 broken links. Shall we try to fix them as part of this PR or should those be handled separately (as likely in places owned by different codeowners).

Link for the [PR](https://github.com/finos/common-cloud-controls/pull/283/files)

**Comment by damienjburks** [comment]
@dogle-scottlogic  thank you! 🎊
