### ISSUE TITLE
Repo Settings: Dismiss Stale Reviews

### ISSUE THREAD

**Issue by eddie-knight** [finos/common-cloud-controls#287]
### Expected Result:

Reviews on pull requests should be reset after a new commit is added, to prevent any mistake or malice from introducing changes that are not aligned with the reviewer's expectations.

### Actual Result:

As seen on the recent PR #285, a new commit was applied after a review was completed and the author was allowed to merge on the authority of the stale review.

(The result was fine, but highlighted a need for settings changes)

### Additional Context:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule#creating-a-branch-protection-rule

**Comment by TheJuanAndOnly99** [comment]
Hi @eddie-knight I enabled the "Dismiss stale pull request approvals when new commits are pushed" setting on the branch protection settings for the main branch.

**Comment by eddie-knight** [comment]
Thank you @TheJuanAndOnly99 !
