### ISSUE TITLE
Retrieve a reference and governance materials from AI Readiness

### ISSUE THREAD

**Issue by damienjburks** [finos/common-cloud-controls#290]
a reference architecture (provided by the AI group)
a set of governance principles/framework (provided by the AI group)

**Comment by robmoffat** [comment]
@ColinEberhardt

@algoritmica 


Can you help with this?

**Comment by lucaborella89** [comment]
@damienjburks I am going to send an invite to the private repo to access the Simple Governance Framework https://github.com/finos/ai-readiness-private/blob/main/governance-framework/Simple-Governance-Framework.md

**Comment by robmoffat** [comment]
@ lucaborella89

**Comment by damienjburks** [comment]
@lucaborella89 I have access - thank you 😃

**Comment by jared-lambert** [comment]
@sublimino can you put your draft service list for the RAG LLM here? Thanks!
