### ISSUE TITLE
OSCAL Training Material

### ISSUE THREAD

**Issue by AdrianHammond** [finos/common-cloud-controls#3]
In the inital NIST WG meeting a question was asked about OSCAL training. In reading up on OSCAL this week I found this [NIST Link](https://pages.nist.gov/OSCAL/learn/presentations/) to OSCAL Instructional Videos, Presentations, and Blogs. So far I have watched this [video](https://cdnapisec.kaltura.com/index.php/extwidget/preview/partner_id/684682/uiconf_id/33598632/entry_id/1_6h8swt6e/embed/dynamic#t=34:57) that I found to be really useful but still need to learn more :-)

**Comment by mcleo-d** [comment]
@jonmuk, @iMichaela and @rachkim00 👋🏻 

It would be good to bring this GitHub Issue to conclusion.

Can you allocate a member of the WG to take the content above and start creating a learning resource as suggested below...

- https://github.com/finos/common-cloud-controls/issues/3#issuecomment-1746448110

Many thanks,

James.

**Comment by mcleo-d** [comment]
@ianmiell agreed to take forward in working group call.

**Comment by ianmiell** [comment]
PR raised here: https://github.com/finos/common-cloud-controls/pull/97
