### ISSUE TITLE
Services for AI Readiness RAG Architecture Milestone

### ISSUE THREAD

**Issue by robmoffat** [finos/common-cloud-controls#314]
## Feature Request

We need to prioritise the following new taxonomy entries:

- Need to do a gap analysis of the available services against the ones defined in the architecture.  @smendis-scottlogic and @jared-lambert tried to figure this out on the call.  Approximately 15 services from Jared:
  - App Service (App Service Plan) [🔗](https://azure.microsoft.com/en-ca/pricing/details/app-service/linux/)
  - Application Insights [🔗](https://azure.microsoft.com/en-ca/pricing/details/monitor/)
  - Azure AI Services [🔗](https://azure.microsoft.com/en-ca/pricing/details/cognitive-services/)
  - Azure Cosmos DB [🔗](https://azure.microsoft.com/en-ca/pricing/details/cosmos-db/autoscale-provisioned/)
  - Bing Search Service [🔗](https://www.microsoft.com/en-us/bing/apis/llm-pricing)
  - Azure AI Document Intelligence [🔗](https://azure.microsoft.com/en-ca/pricing/details/form-recognizer/#pricing) 
  - Azure Function(App Service Plan) [🔗](https://azure.microsoft.com/en-ca/pricing/details/functions/#pricing)
  - Azure Key Vault [🔗](https://azure.microsoft.com/en-us/pricing/details/key-vault/)
  - Log Analytics workspace [🔗](https://azure.microsoft.com/en-ca/pricing/details/monitor/)
  - Azure Logic App [🔗](https://azure.microsoft.com/en-us/pricing/details/logic-apps/)
  - Azure AI Search [🔗](https://azure.microsoft.com/en-ca/pricing/details/search/#pricing)
  - Azure OpenAI [🔗](https://azure.microsoft.com/en-ca/pricing/details/cognitive-services/openai-service/)
  - Storage account [🔗](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview)
  - Azure Active Directory [🔗](https://www.microsoft.com/en-sg/security/business/microsoft-entra-pricing?rtc=1)

- Key Services that we should focus on might be:
  - Azure Open AI
  - Storage Account
  - Azure Key Vault
  - Log Analytics

@Alexstpierrework, @smendis-scottlogic  and @jared-lambert to work on prioritisation, genericising the names and removing items that we've already done (e.g. Azure Cosmos DB is an RDBMS, which is defined already).

**Comment by smendis-scottlogic** [comment]
We only have the **Azure Storage Account** covered from this list

**Comment by eddie-knight** [comment]
I'll be meeting with members of the AI Readiness group tomorrow to discuss strategies for bringing their work into the CCC context.

Planning to share more about this on the meeting later today, and happy to have anyone else join who is interested.

**Comment by jared-lambert** [comment]
@sublimino can you copy in your list from the AI SIG here?
