### ISSUE TITLE
Lay the groundwork for release candidate automation

### ISSUE THREAD

**Issue by damienjburks** [finos/common-cloud-controls#315]
### Description of Problem:

...what _problem_ are you trying to solve that the project doesn't currently solve?

...please resist the temptation to describe your request in terms of a solution. Job Story form ("When [triggering condition], I want to [motivation/goal], so I can [outcome].") can help ensure you're expressing a problem statement.

### Potential Solutions:

...clearly and concisely describe what you want to happen. Add any considered drawbacks.

... if you've considered alternatives, clearly and concisely describe those too.

**Comment by eddie-knight** [comment]
@damienjburks — What do you think about using golang to marshal all the YAML from controls, threats, and taxonomy features, then we smash them together inmem to craft our desired outputs.

- a single large markdown (already have the code for that in a PR)
- the same content into PDF through something like this ([cursory search](https://appliedgo.net/pdf/))
- some massaged version of that into OSCAL

We could probably set up a single little CLI program that can be dropped into a release action/workflow.

**Comment by iMichaela** [comment]
> @damienjburks — What do you think about using golang to marshal all the YAML from controls, threats, and taxonomy features, then we smash them together inmem to craft our desired outputs.
> 
> * a single large markdown (already have the code for that in a PR)
> * the same content into PDF (through something like this [cursory search](https://appliedgo.net/pdf/))
> * some massaged version of that into OSCAL
> 
> We could probably set up a single little CLI program that can be dropped into a release action/workflow.

OSCAL supports YAML.. and could represent all this data  controls, threats, and taxonomy features. Need to discuss if one gigantic file is better than separating data different OSCAL models...

**Comment by eddie-knight** [comment]
@iMichaela there is definitely an agreement that we want to have OSCAL outputs. 

The issue I'm trying to navigate is that we don't currently have any contributors who have expressed a comfort with upskilling to write the CCC taxonomy and controls in OSCAL format.

The proposal which has gained some steam this week involves a multi-file simplified-YAML workflow for each phase of developing the taxonomy/threats/controls, while more nuanced or complex efforts will be automated in the release process that is being brainstormed here.

**Comment by damienjburks** [comment]
> @damienjburks — What do you think about using golang to marshal all the YAML from controls, threats, and taxonomy features, then we smash them together inmem to craft our desired outputs.
> 
> 
> 
> - a single large markdown (already have the code for that in a PR)
> 
> - the same content into PDF (through something like this [cursory search](https://appliedgo.net/pdf/))
> 
> - some massaged version of that into OSCAL
> 
> 
> 
> We could probably set up a single little CLI program that can be dropped into a release action/workflow.

I'm think it's a great idea; I have to take a little training on Go in order to contribute to this. YAML already provides us a lot of opportunity to introduce automation into creating the artifacts for a release. 

Now, when it comes down to the assessment layer for validating our controls, I'd definitely need @mlysaght2017's insight into it. 

I also know OSCAL supports YAML files so perhaps we can start thinking about how to integrate these into those models, or find a neat way to convert the controls into an OSCAL acceptable format?

**Comment by iMichaela** [comment]
AS I mentioned earlier ... IBM trestle is open source and could be worth trying to have the contributors produce Markdown or spreadsheets that Trestle would convert to OSCAL JSON and form there to any format with oscal-cli
