### ISSUE TITLE
Convert controls template (yaml-based) into OSCAL representation 

### ISSUE THREAD

**Issue by mlysaght2017** [finos/common-cloud-controls#322]
### Description of Problem:

We need to convert the yaml-based control catalog (see  #271 ) for the object storage service into OSCAL (either as a Component Definition or as a Catalog/Profile)

### Potential Solutions:

Script to convert yaml control file into OSCAL representation

**Comment by iMichaela** [comment]
Data captured in the https://github.com/finos/common-cloud-controls/pull/271/files/68902658c7f38c6becf81c7ee0f1530de02cc1cc#diff-213c905bb4aee9f1e45fdbe55bdf5403fad8e48a97ed5e7856638a7886dd89d4 is suitable for an OSCAL Catalog. A Component Definition will describe how each component documented by a CDef satisfies or should satisfy all or a subset of controls (aka OSCAL profile or baseline).
