### ISSUE TITLE
09/05/2024 All Hands Meeting

### ISSUE THREAD

**Issue by Alexstpierrework** [finos/common-cloud-controls#332]
## Date

MM/DD/YYYY - 12:00 ET / 17:00 UK

- [Join Zoom Meeting](https://zoom.us/j/94416168360)
- Meeting ID: 944 1616 8360
- Passcode: 042805
- [Find your local number](https://zoom.us/u/apjhwwA3K)
- [Copy this meeting to your calendar](https://calendar.finos.org/)

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).
- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).
- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.
- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] [Project board](https://github.com/orgs/finos/projects/78/views/11) walkthrough
- [x] Working Session - Resolving WG Constraints
- [x] AOB, Q&A & Adjourn (5mins)

## Untracked attendees

- Fullname, Affiliation, (optional) GitHub username
- ...

**Comment by smendis-scottlogic** [comment]
Sonali Mendis / Scott Logic

**Comment by eddie-knight** [comment]
:wave: :shipit: Eddie Knight / Sonatype

**Comment by grudra7714** [comment]
Rudra Gupta / Krumware

**Comment by robmoffat** [comment]
Rob Moffat / FINOS

**Comment by rgriffiths-scottlogic** [comment]
Rob Griffiths / Scott Logic

**Comment by ojeb2** [comment]
Oli Bage / LSEG

**Comment by robmoffat** [comment]
## Minutes


### Actions From Last Time

ACTION: @Alexstpierrework, @smendis-scottlogic and @jared-lambert to work on prioritisation, genericising the names and removing items that we've already done (e.g. Azure Cosmos DB is an RDBMS, which is defined already).

## Working Group Updates

### Duplication Reduction

Working on analysis of: 

- OSCAL
- Mitre Enginuity
- CDMC

@jared-lambert thinks this is lower priority than the AI-Readiness / CCC use case work stream, so the focus is going into that at the moment.   

There's a workshop in NYC in a couple of weeks with AI Readiness at Microsoft, preparing for that.

**Comment by jared-lambert** [comment]
Jared Lambert / Microsoft

**Comment by JEFFGALLUCCI** [comment]
Jeff Gallucci / Microsoft
