### ISSUE TITLE
Develop Artifact Releasing Tool

### ISSUE THREAD

**Issue by damienjburks** [finos/common-cloud-controls#339]
### Description of Problem:

At the moment, we do not have a formalized process for releasing artifacts and sharing them with our stakeholders. So, to address this gap, we need to develop the artifact-releasing tool first. This tool should be responsible for the following:

1. Compiling all of the YAML files (controls, threats, features, etc.)
2. Converting YAML files into human-readable format (PDF, MD)
3. Converting YAML files into OSCAL-supported format and files
4. Create a version-controlled zip file or package with all the artifacts inside.

**Comment by damienjburks** [comment]
@eddie-knight I've created the issue & mapped it to the PR - will update the description later.

**Comment by damienjburks** [comment]
Architecture diagram is located in #334 - we are using Golang for this.

**Comment by sshiells-scottlogic** [comment]
Sorry if I missed this, is there a plan for storing versions of the compiled output?

I think it would be quite nice, if there was a "latest" verson of the markdown, along with the cal ver version, and that way people would be able to track the changes via the file history diff to more easily see the changes via the diff?

**Comment by eddie-knight** [comment]
Yeah @sshiells-scottlogic, the goal is for the "production ready" assets to be stored in GitHub Releases
