### ISSUE TITLE
Formalise yaml schemas

### ISSUE THREAD

**Issue by sshiells-scottlogic** [finos/common-cloud-controls#364]
### Description of Problem:

Currently we have example template files for features, controls, threads at meta data. Having templates instead of schemas make it more difficult to version control and validate.

### Potential Solutions:

Produce yaml schemas based on the current template files.

**Comment by dogle-scottlogic** [comment]
https://github.com/finos/common-cloud-controls/pull/369

**Comment by iMichaela** [comment]
Does it make sense to use the OSCAL YAML schema for validation. In the examples I created long ago, I included a Makefile that invokes the oscal-cli tool for validation and conversion into all supported formats (XML, JSON, YAML). The Makefile can be used for local development to validate oscal artifacts and can be invoked from CI/CD pipeline.
