### ISSUE TITLE
Review Repo Structure

### ISSUE THREAD

**Issue by sshiells-scottlogic** [finos/common-cloud-controls#374]
As the project grows we should review the repo structure to make sure it grows in a manageable way.

(see comment on https://github.com/finos/common-cloud-controls/pull/369/files#diff-877890ee489562630e22580a4f8f24d965b2a4fad60c9ff5618fc59e9a4386fc)

**Comment by sshiells-scottlogic** [comment]
![image](https://github.com/user-attachments/assets/6696b1ab-04c0-46bf-a253-5c6c497eaf68)

**Comment by sshiells-scottlogic** [comment]
@eddie-knight  see above for suggested format. I appreciate that might not be too clear. If I get time on Monday let me see if I can make a branch with the changes. 

Maybe it might be best if I make a branch and we can sync early next week and have a quick chat and work throgh possible options?

**Comment by eddie-knight** [comment]
Yeah an example might be easier. We don't want to overload the top level, but I might be misunderstanding the notes
