### ISSUE TITLE
Create guidelines for Threat Model contributions

### ISSUE THREAD

**Issue by eddie-knight** [finos/common-cloud-controls#399]
We have the following concepts defined:

- Threat models are required for assurance level 2+
- Threat model author and URL can be tracked in service metadata

We also need to address these questions in the form of guidelines and/or examples:

- Where should threat models live?
- What content is required for a threat model to be accepted?
- What is the proper format or structure for a threat model, if any?

**Comment by eddie-knight** [comment]
cc/ @sublimino @vicenteherrera

**Comment by mlysaght2017** [comment]
To review CNCF Lightweight Threat Model approach: https://github.com/cncf/tag-security/issues/903
