### ISSUE TITLE
Engage with NIST WG to agree OSCAL versioning strategy when referencing mitigated threats from OSCAL descriptions

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#4]
## Description

It was discussed during [August 10th 2023 Common Cloud Controls - Engage with NIST on Controls](https://github.com/finos/common-cloud-controls/issues/2) that the WG should agree the CCC OSCAL versioning strategy when referencing or describing mitigated `threats` from OSCAL descriptions.

It was raised on the call that the CCC OSCAL should not duplicate threat descriptions,  but reference a versioned `threat` that lives as the `authoritative source`. 

It was also raised in the WG that the MITRE working group should define, reference and version threats that don't appear in the MITRE definitions.

## Success Criteria
1. The WG agrees how `threats` should be referenced or described within the CCC OSCAL.
2. The WG agrees the version control strategy so the OSCAL refers to the `threats` at a specific point in time until the next CCC OSCAL release.

**Comment by mcleo-d** [comment]
@iMichaela, @jonmuk, @rachkim00,

This item be prioritised for completion as a markdown contribution or closed if not required.

Kind regards,

James.

**Comment by iMichaela** [comment]
One way of documenting the threats in OSCAL was demonstrated by Robert Ficcaglia and Francesco Beltramini in their presentation: video: https://cdnapisec.kaltura.com/index.php/extwidget/preview/partner_id/684682/uiconf_id/31013851/entry_id/1_e861yoyu/embed/dynamic#t=8:23

**Comment by mcleo-d** [comment]
From @iMichaela - Group related issues so when one is closed, all are closed.
