### ISSUE TITLE
Follow up on 7th Sept meeting.

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#40]
### Discussed in https://github.com/finos/common-cloud-controls/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **ianmiell** September 21, 2023</sup>
Hi @jonmuk @iMichaela,

As discussed in the meeting of 7th September, I'm introducing you to my colleagues @gusfcarvalho and Onsel (invite pending, https://github.com/onselakin).

As a reminder of the context, Onsel and Gustavo are working with the OSCAL standard as part of an open source project we're working on. They've had some lessons learned as a result and we're keen to discuss them with you, as well as hear from you about your perspectives on it.

If you'd like to continue the discussion by email, my email is: ian.miell [at] container-solutions.com (I don't think I have your mails). Anyone else with an interest in this group is welcome to join us.

Ian</div>

**Comment by mcleo-d** [comment]
Hi @ianmiell and @iMichaela,

Can you help move the actions from this GitHub Issue forward with the `OSCAL representation of FINOS CCC` working group or `close` if `done`.

Thank you for your help and collaboration,

James.

**Comment by ianmiell** [comment]
I'm happy to close. Thanks.

For reference, the Compliance Framework open source project is here: https://github.com/compliance-framework

**Comment by iMichaela** [comment]
## 11/09/2023 ##
During the meeting we decided this issue can be closed.
