### ISSUE TITLE
Should we move guidelines to a higher dir level?

### ISSUE THREAD

**Issue by eddie-knight** [finos/common-cloud-controls#417]
Currently guidelines are nested pretty deep. Unintuitive. 

Can we improve this?

**Comment by sshiells-scottlogic** [comment]
Yeah, we have an [open issue](https://github.com/finos/common-cloud-controls/issues/374) to review and improve the structure. I will come up with a proposal but we might want to hold off until the dust has settleed on OSFF before we make any changes?
