### ISSUE TITLE
Get all the repo content into a passing state with the CI schema check

### ISSUE THREAD

**Issue by eddie-knight** [finos/common-cloud-controls#425]
## Problem

Right now nothing can really pass the CI checks because we have too many files failing.

## Solution

We need to just start going through every single file to get them into a good state one at a time. Once everything is cleaned up, we can require the CI check to pass on all subsequent PRs.

## Previous solution proposal

_This idea was thrown out because we rely on schema validation. If the schemas have a bad change or failing edge cases, we need to know immediately before approving a schema change._

Our CI checks currently evaluate all files on all PRs. Instead, they should only check items that have been modified.

Potential resource:

- https://github.com/tj-actions/changed-files
- example: https://github.com/procore-oss/blueprinter/blob/7cc97b48bfdc538d8f60a5d96b2c4240aa84dc3f/.github/workflows/release.yaml#L18

**Comment by sshiells-scottlogic** [comment]
Is this temporary until things are more stable?

I'd be wary of introducing this permanently as it could open the door to schema changes etc. Without the changes being cascaded throughout the repo (which I presume is what we would want)?

Would a better task be to update the current violations and bring those in line?

**Comment by eddie-knight** [comment]
Fair point @sshiells-scottlogic — if we just get the repo to a healthy state we can start having universal enforcement. Then bad schema changes will be prevented in the future.
