### ISSUE TITLE
Add common control snippets and snippet documentation

### ISSUE THREAD

**Issue by sshiells-scottlogic** [finos/common-cloud-controls#438]
Add snippets for common controls in the same way as we have for common features and common threats.

Also add documentation on how to use all of the snippets which are available:

- metadata file template
- features file template
- additional feature item
- common features
- threats file template
- additional threat item
- common threats
- controls file template
- additional control item
- common controls

**Comment by damienjburks** [comment]
@dogle-scottlogic

**Comment by damienjburks** [comment]
@eddie-knight is there someone we can speak to? i can't assign @dogle-scottlogic  to the ticket.

**Comment by eddie-knight** [comment]
Yep, just need to ask help@finos.org for the addition to @finos/common-cloud-controls
