### ISSUE TITLE
Define which cloud service providers are accepting the initial OSCAL definitions 

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#45]
_**Due date : 19th January 2024**_

This GitHub issues represents part of the roadmap defined by the OSCAL working group on https://github.com/finos/common-cloud-controls/issues/13

```[tasklist]
### Tasks
- [ ] Define which cloud service providers are accepting the initial OSCAL definitions
- [ ] Investigate and define how are their services implemented and tested?
```

**Comment by crawfordchanel** [comment]
Complete as per Michaela's comment 10.11.23
