### ISSUE TITLE
Request for clarification around very similar control tests CCC.C04.TR01 and CCC.C05.TR02

### ISSUE THREAD

**Issue by sarahecraddock** [finos/common-cloud-controls#495]
## Support Question
I am working on the Azure Raid for Azure Blob Storage and I have a couple of questions around what was intended for specific control tests...

There are two control tests, **CCC.C04.TR01** and **CCC.C05.TR02**, which appear to be testing the same thing.
**CCC.C04.TR01**: The service logs all access attempts, including successful and failed login attempts.
**CCC.C05.TR02**: The service logs all access attempts from untrusted entities, including failed connection attempts.

What's the intended difference between these two?

**Comment by mlysaght2017** [comment]
@sarahecraddock @eddie-knight 

There is a subtle difference between the two TRs across the two separate controls, but it should be centred more on alerting rather than logging. 

Right now, CCC.C05.TR02, is effectively a duplication of CCC.C04.TR01. 

I have removed CCC.C05.TR02 in #505
