### ISSUE TITLE
Taxonomy Working Group to Evaluate FOCUS Synergies with Common Cloud Controls

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#57]
## Description

The Taxonomy Working Group should evaluate the FinOps FOCUS project to determine synergices with Common Cloud Controls as discussed during https://github.com/finos/common-cloud-controls/issues/25#issuecomment-1739679125

The FOCUS resources provided by @udam-f2 are below ...

## FOCUS Resources

FOCUS stands for FinOps Open Cost and Usage Specification - which aims to normalize cost and usage data across cloud, Saas and other areas (licensing, internal cloud, labor etc.) from a cost and usage data perspective. FOCUS is an open-source project under the Linux Foundation (similar to CCC). We have a v1.0 planned for Mid November 2023.

FOCUS mappings for Service Categories:
Spec: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/dimensions/servicecategory.md

Supporting content: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/supporting_content/dimensions/servicecategory.md

Service mapping work done as a part of FOCUS data converters:
https://docs.google.com/spreadsheets/d/1s8FYVxAkDs2aeHPckEJrjA36Vpn4HKXpkXU0L-O8IAY/edit#gid=2123051243

**Comment by smendis-scottlogic** [comment]
Looks like the links from project FOCUS has changed. Please use following links as the links in the description are broken.

FOCUS mappings for Service Categories:
Spec: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/service_category-dimension/specification/dimensions/servicecategory.md

Supporting content: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/service_category-dimension/supporting_content/dimensions/servicecategory.md

**Comment by AdrianHammond** [comment]
Hi @smendis-scottlogic @sshiells-scottlogic @udam-f2  @mark-rushing - Hi All, we discussed this issue in todays working group. On the call the belief was that this had been discussed previously and their was agreement that CCC would not look to tie itself to a higher level taxonomy e.g. Focus.  Do you have a view on this?  If you think we need to have short working call to discuss and I get one setup.  Many thanks Adrian

**Comment by smendis-scottlogic** [comment]
@crawfordchanel Hi Chanel, I looked into FOCUS top level taxonomies and absorbed what was important to our top level taxonomy

**Comment by AdrianHammond** [comment]
Hi @smendis-scottlogic  - Just to confirm you included in [common cloud services](https://github.com/finos/common-cloud-controls/blob/main/services/common-cloud-services.md). Thanks
