### ISSUE TITLE
Identify where to add test cases and threats within OSCAL. Working in collaboration with NIST.

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#64]
_**Due date : 15th December 2023**_

.... success criteria required.
```[tasklist]
### Tasks
```

**Comment by mcleo-d** [comment]
@iMichaela, @jonmuk, @rachkim00

It would be great to bring this to conclusion with a markdown document committed to the repo that points to the correct OSCAL attributes that should be utilised.

Many thanks,

James.

**Comment by rachkim00** [comment]
Same issue was raised from MITRE/Test Case working group: [#75](https://github.com/finos/common-cloud-controls/issues/75). The discussion is being happened there now.

**Comment by mcleo-d** [comment]
Issue closed as a duplication of #75.
