### ISSUE TITLE
Remove Moe Matar as FINOS CCC Maintainer?

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#94]
Dear @moematar and FINOS CCC Maintainers,

I'd like to ask whether @moematar should be removed as a FINOS Common Cloud Controls maintainer given his employment status with Citi.

Thank you for your help.

James.

**Comment by AdrianHammond** [comment]
If someone is willing to contribute to the project and commit to be a maintainer should we be discouraging them from doing so?

**Comment by mcleo-d** [comment]
Hi @AdrianHammond - No, not at all. The more people who are committed to leading and pushing the project forward, the better! 😄 

I hope this helps.

James.

**Comment by mcleo-d** [comment]
It has been agreed that @moematar will remain a FINOS CCC maintainer until he understands the capacity of his new role.
